ALIASES: dict[str, str] = {
    "arduino nano every": "Arduino Nano",
    "arduino nano": "Arduino Nano",
    "arduino uno r3": "Arduino Uno",
    "arduino uno": "Arduino Uno",
    "esp32 devkit v1": "ESP32 Dev Board",
    "esp32-wroom-32": "ESP32 Dev Board",
    "esp32 cam": "ESP32-CAM",
    "esp32-cam ai thinker": "ESP32-CAM",
    "esp32-cam": "ESP32-CAM",
    "hc-sr04": "HC-SR04 Ultrasonic Sensor",
    "ultrasonic sensor": "HC-SR04 Ultrasonic Sensor",
    "hc-05": "Bluetooth HC-05 Module",
    "hc05": "Bluetooth HC-05 Module",
    "bluetooth module": "Bluetooth HC-05 Module",
    "l298n": "L298N Motor Driver",
    "tb6612": "TB6612FNG Motor Driver",
    "drv8833": "TB6612FNG Motor Driver",
    "tt motor": "Small DC Motor",
    "tt gear motor": "Small DC Motor",
    "tt geared dc motor": "Small DC Motor",
    "dc motor": "Small DC Motor",
    "n20": "N20 Gear Motor",
    "sg90": "SG90 Micro Servo",
    "mg90s": "SG90 Micro Servo",
    "mg996r": "MG996R High Torque Servo",
    "servo": "SG90 Micro Servo",
    "ws2812b": "NeoPixel Strip",
    "neopixel": "NeoPixel Strip",
    "led strip": "NeoPixel Strip",
    "ssd1306": "0.96 inch OLED Display",
    "oled": "0.96 inch OLED Display",
    "bme280": "BMP280 Pressure Sensor",
    "bmp280": "BMP280 Pressure Sensor",
    "dht22": "DHT22 Temperature/Humidity Sensor",
    "soil moisture": "Soil Moisture Sensor",
    "capacitive soil moisture": "Soil Moisture Sensor",
    "pir": "PIR Motion Sensor",
    "hc-sr501": "PIR Motion Sensor",
    "mfrc522": "RFID RC522 Module",
    "rc522": "RFID RC522 Module",
    "relay": "Relay Module",
    "mosfet": "MOSFET Module",
    "irlz44n": "MOSFET Module",
    "water pump": "Mini Water Pump",
    "peristaltic pump": "Mini Water Pump",
    "buck converter": "Adjustable Buck Converter",
    "lm2596": "Adjustable Buck Converter",
    "xl4015": "Adjustable Buck Converter",
    "boost converter": "Boost Converter",
    "ams1117": "AMS1117 Linear Regulator",
}


CATEGORY_HINTS: dict[str, list[str]] = {
    "microcontroller": ["arduino", "esp32", "pico"],
    "motor": ["motor", "pump", "fan"],
    "servo": ["servo"],
    "led": ["led", "neopixel", "ws2812"],
    "sensor": ["sensor", "pir", "dht", "bme", "bmp", "rfid", "ultrasonic"],
    "driver": ["driver", "mosfet", "relay", "l298n", "tb6612", "drv8833"],
    "regulator": ["buck", "boost", "regulator", "lm2596", "xl4015", "ams1117"],
    "power": ["battery", "adapter", "supply", "18650", "lipo", "usb"],
}
